### ISSUE TITLE
Timestamp is not in order

### ISSUE THREAD

**Issue by kaiduanx** [PlatformLab/NanoLog#36] opened 2020-07-16 22:16 UTC
The issue is that the timestamp is not in the right order. The time stamp of the log at 59 line is older than the timestamp of the log at 64 line. I only commented out the runBenMark() function.

~/NanoLog/sample$ ./decompressor decompress /tmp/logFile 
2020-07-16 18:12:41.-00022964 main.cc:59 NOTICE[0]: A string, pointer, number, and float: 'Hello World', 0x7ffd9db8d8bc, 512, 3.141590
2020-07-16 18:12:41.-00022108 main.cc:64 NOTICE[0]: Shortend String: 'Hello World' and shortend float 3.14

# Decompression Complete after printing 2 log messages

~/NanoLog/sample$ git diff
diff --git a/sample/main.cc b/sample/main.cc
index af67390..c4523cb 100644
--- a/sample/main.cc
+++ b/sample/main.cc
@@ -64,7 +64,7 @@ int main(int argc, char** argv) {
                      3.14159);
 
 
-    runBenchmark();
+    //runBenchmark();
 
     // Optional: Flush all pending log messages to disk
     NanoLog::sync();

**Comment by syang0** [comment] 2020-07-16 22:30
Hi kaiduanx,

I think the issue is related to #28 where log messages at the beginning of the file can sometimes have a negative nanosecond timestamp (notice the little dash character `-` after the decimal point). The timestamps are still in order; it's just that nanosecond count is printed out as a negative value. I suspect the fix may be just to add an if-condition in the decompressor to check for this case. However, I'm not able to reproduce the problem on my setup.

Could you send me your log file, so I can verify the fix?

Best Regards,
Stephen Yang

**Comment by kaiduanx** [comment] 2020-07-16 22:41
Please send an email to kaiduanx@yahoo.ca, I will send the file to you.

**Comment by syang0** [comment] 2020-07-16 22:52
Actually, can you post the file here? You can attach files to GitHub comments; simply drag the file into the text field.

Instructions: [https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests)

Example File: [ProofOfConcept.txt](https://github.com/PlatformLab/NanoLog/files/4934743/ProofOfConcept.txt)

**Comment by kaiduanx** [comment] 2020-07-17 00:01
[logFile.log](https://github.com/PlatformLab/NanoLog/files/4934977/logFile.log)

**Comment by syang0** [comment] 2020-07-17 10:35
Hey kaiduanx,

The problem should be fixed now. Give it a try and let me know if it works.

Best Regards,
Stephen Yang

**Comment by kaiduanx** [comment] 2020-07-17 13:39
@syang0 , the problem is fixed, please see the following log. Many thanks, @syang0 

~/NanoLog/sample$ ./decompressor decompress /tmp/logFile 
2020-07-17 09:34:53.999992889 main.cc:59 NOTICE[0]: A string, pointer, number, and float: 'Hello World', 0x7ffdf907d2dc, 512, 3.141590
2020-07-17 09:34:53.999993750 main.cc:64 NOTICE[0]: Shortend String: 'Hello World' and shortend float 3.14


# Decompression Complete after printing 2 log messages

**Closed** 2020-07-20 00:15 UTC
